config/routes.rb
MousehouseRails::Application.routes.draw do
  resources :buildings

  resources :rooms

  resources :litters

  resources :breeding_pairs

  resources :mice

  resources :cages

  resources :mouse_racks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show
  
  namespace :api do
    namespace :v1  do
      match 'sign_in' => 'tokens#create', :via => :post
      match 'sign_out' => 'tokens#destroy', :via => :post
      #resources :tokens, :only => [:create, :destroy]
      resources :cages
      resources :mouse_racks
    end
  end
  
  
end

app/models/breeding_pair.rb
class BreedingPair
  include Mongoid::Document
  field :sire_id, :type => Integer
  field :dam_id, :type => Integer
end

app/controllers/api/v1/breeding_pairs_controller.rb
class Api::V1::BreedingPairsController < Api::V1::ApiController
  before_filter :set_breeding_pair, :except => [:index, :create]
  # GET /breeding_pairs
  # GET /breeding_pairs.json
  def index
    @breeding_pairs = current_user.breeding_pairs.all

    respond_to do |format|
      format.json { render json: @breeding_pairs }
    end
  end

  # GET /breeding_pairs/1
  # GET /breeding_pairs/1.json
  def show
    @breeding_pair = BreedingPair.find(params[:id])

    respond_to do |format|
      format.json { render json: @breeding_pair }
    end
  end

  # POST /breeding_pairs
  # POST /breeding_pairs.json
  def create
    @breeding_pair = current_user.breeding_pair.new(params[:breeding_pair])

    respond_to do |format|
      if @breeding_pair.save
        format.json { render json: @breeding_pair, status: :created, location: @breeding_pair }
      else
        format.json { render json: @breeding_pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breeding_pairs/1
  # PUT /breeding_pairs/1.json
  def update
    respond_to do |format|
      if @breeding_pair.update_attributes(params[:breeding_pair])
        format.json { head :no_content }
      else
        format.json { render json: @breeding_pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeding_pairs/1
  # DELETE /breeding_pairs/1.json
  def destroy
    @breeding_pair.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end
  
  protected
    def set_breeding_pair
      @breeding_pair = current_user.breeding_pair.find(params[:id])
    end
end

app/controllers/breeding_pairs_controller.rb
class BreedingPairsController < ApplicationController
  # GET /breeding_pairs
  # GET /breeding_pairs.json
  def index
    @breeding_pairs = BreedingPair.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @breeding_pairs }
    end
  end

  # GET /breeding_pairs/1
  # GET /breeding_pairs/1.json
  def show
    @breeding_pair = BreedingPair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @breeding_pair }
    end
  end

  # GET /breeding_pairs/new
  # GET /breeding_pairs/new.json
  def new
    @breeding_pair = BreedingPair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @breeding_pair }
    end
  end

  # GET /breeding_pairs/1/edit
  def edit
    @breeding_pair = BreedingPair.find(params[:id])
  end

  # POST /breeding_pairs
  # POST /breeding_pairs.json
  def create
    @breeding_pair = BreedingPair.new(params[:breeding_pair])

    respond_to do |format|
      if @breeding_pair.save
        format.html { redirect_to @breeding_pair, notice: 'Breeding pair was successfully created.' }
        format.json { render json: @breeding_pair, status: :created, location: @breeding_pair }
      else
        format.html { render action: "new" }
        format.json { render json: @breeding_pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breeding_pairs/1
  # PUT /breeding_pairs/1.json
  def update
    @breeding_pair = BreedingPair.find(params[:id])

    respond_to do |format|
      if @breeding_pair.update_attributes(params[:breeding_pair])
        format.html { redirect_to @breeding_pair, notice: 'Breeding pair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @breeding_pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeding_pairs/1
  # DELETE /breeding_pairs/1.json
  def destroy
    @breeding_pair = BreedingPair.find(params[:id])
    @breeding_pair.destroy

    respond_to do |format|
      format.html { redirect_to breeding_pairs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/breeding_pairs_helper.rb
module BreedingPairsHelper
end

app/views/breeding_pairs/_form.html.erb
<%= form_for(@breeding_pair) do |f| %>
  <% if @breeding_pair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breeding_pair.errors.count, "error") %> prohibited this breeding_pair from being saved:</h2>

      <ul>
      <% @breeding_pair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sire_id %><br />
    <%= f.number_field :sire_id %>
  </div>
  <div class="field">
    <%= f.label :dam_id %><br />
    <%= f.number_field :dam_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breeding_pairs/edit.html.erb
<h1>Editing breeding_pair</h1>

<%= render 'form' %>

<%= link_to 'Show', @breeding_pair %> |
<%= link_to 'Back', breeding_pairs_path %>

app/views/breeding_pairs/index.html.erb
<h1>Listing breeding_pairs</h1>

<table>
  <tr>
    <th>Sire</th>
    <th>Dam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @breeding_pairs.each do |breeding_pair| %>
  <tr>
    <td><%= breeding_pair.sire_id %></td>
    <td><%= breeding_pair.dam_id %></td>
    <td><%= link_to 'Show', breeding_pair %></td>
    <td><%= link_to 'Edit', edit_breeding_pair_path(breeding_pair) %></td>
    <td><%= link_to 'Destroy', breeding_pair, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Breeding pair', new_breeding_pair_path %>

app/views/breeding_pairs/new.html.erb
<h1>New breeding_pair</h1>

<%= render 'form' %>

<%= link_to 'Back', breeding_pairs_path %>

app/views/breeding_pairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sire:</b>
  <%= @breeding_pair.sire_id %>
</p>

<p>
  <b>Dam:</b>
  <%= @breeding_pair.dam_id %>
</p>


<%= link_to 'Edit', edit_breeding_pair_path(@breeding_pair) %> |
<%= link_to 'Back', breeding_pairs_path %>