config/routes.rb
MousehouseRails::Application.routes.draw do
  resources :buildings

  resources :rooms

  resources :litters

  resources :breeding_pairs

  resources :mice

  resources :cages

  resources :mouse_racks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show
  
  namespace :api do
    namespace :v1  do
      match 'sign_in' => 'tokens#create', :via => :post
      match 'sign_out' => 'tokens#destroy', :via => :post
      #resources :tokens, :only => [:create, :destroy]
      resources :cages
      resources :mouse_racks
    end
  end
  
  
end

app/models/cage.rb
class Cage
  include Mongoid::Document
  field :label, :type => String
  field :protocol_id, :type => Integer
  field :mouse_rack_id, :type => Integer
  field :row, :type => Integer
  field :column, :type => Integer
  field :user_id, :type => Integer
  field :created_at, :type => Time
  field :created_by, :type => Integer
  field :modified_on, :type => Time
  field :bodified_by, :type => Integer
end

app/controllers/api/v1/_cages_controller.rb
class Api::V1::CagesController < Api::V1::ApiController
  before_filter :set_cage, :except => :index

  def index
    @cages = current_user.cages
    render json: @cages
  end

  protected
    def set_cage
      @cage = current_user.cages.find(params[:id])
    end
end

app/controllers/api/v1/cages_controller.rb
class Api::V1::CagesController < Api::V1::ApiController
  before_filter :set_cage, :except => [:index, :create]
  
  # GET /cages
  # GET /cages.json
  def index
    @cages = current_user.cages

    respond_to do |format|
      format.json { render json: @cages }
    end
  end

  # GET /cages/1
  # GET /cages/1.json
  def show

    respond_to do |format|
      format.json { render json: @cage }
    end
  end

  # POST /cages
  # POST /cages.json
  def create
    @cage = current_user.cages.new(params[:cage])

    respond_to do |format|
      if @cage.save
        format.json { render json: @cage, status: :created, location: @cage }
      else
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cages/1
  # PUT /cages/1.json
  def update
    
    respond_to do |format|
      if @cage.update_attributes(params[:cage])
        format.json { head :no_content }
      else
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cages/1
  # DELETE /cages/1.json
  def destroy
    @cage.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end
  
  protected
    def set_cage
      @cage = current_user.cages.find(params[:id])
    end
end

app/controllers/cages_controller.rb
class CagesController < ApplicationController
  # GET /cages
  # GET /cages.json
  def index
    @cages = Cage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cages }
    end
  end

  # GET /cages/1
  # GET /cages/1.json
  def show
    @cage = Cage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cage }
    end
  end

  # GET /cages/new
  # GET /cages/new.json
  def new
    @cage = Cage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cage }
    end
  end

  # GET /cages/1/edit
  def edit
    @cage = Cage.find(params[:id])
  end

  # POST /cages
  # POST /cages.json
  def create
    @cage = Cage.new(params[:cage])

    respond_to do |format|
      if @cage.save
        format.html { redirect_to @cage, notice: 'Cage was successfully created.' }
        format.json { render json: @cage, status: :created, location: @cage }
      else
        format.html { render action: "new" }
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cages/1
  # PUT /cages/1.json
  def update
    @cage = Cage.find(params[:id])

    respond_to do |format|
      if @cage.update_attributes(params[:cage])
        format.html { redirect_to @cage, notice: 'Cage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cages/1
  # DELETE /cages/1.json
  def destroy
    @cage = Cage.find(params[:id])
    @cage.destroy

    respond_to do |format|
      format.html { redirect_to cages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cages_helper.rb
module CagesHelper
end

app/views/cages/_form.html.erb
<%= form_for(@cage) do |f| %>
  <% if @cage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cage.errors.count, "error") %> prohibited this cage from being saved:</h2>

      <ul>
      <% @cage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :protocol_id %><br />
    <%= f.number_field :protocol_id %>
  </div>
  <div class="field">
    <%= f.label :mouse_rack_id %><br />
    <%= f.number_field :mouse_rack_id %>
  </div>
  <div class="field">
    <%= f.label :row %><br />
    <%= f.number_field :row %>
  </div>
  <div class="field">
    <%= f.label :column %><br />
    <%= f.number_field :column %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.time_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.number_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :modified_on %><br />
    <%= f.time_select :modified_on %>
  </div>
  <div class="field">
    <%= f.label :bodified_by %><br />
    <%= f.number_field :bodified_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cages/edit.html.erb
<h1>Editing cage</h1>

<%= render 'form' %>

<%= link_to 'Show', @cage %> |
<%= link_to 'Back', cages_path %>

app/views/cages/index.html.erb
<h1>Listing cages</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Protocol</th>
    <th>Mouse rack</th>
    <th>Row</th>
    <th>Column</th>
    <th>User</th>
    <th>Created at</th>
    <th>Created by</th>
    <th>Modified on</th>
    <th>Bodified by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cages.each do |cage| %>
  <tr>
    <td><%= cage.label %></td>
    <td><%= cage.protocol_id %></td>
    <td><%= cage.mouse_rack_id %></td>
    <td><%= cage.row %></td>
    <td><%= cage.column %></td>
    <td><%= cage.user_id %></td>
    <td><%= cage.created_at %></td>
    <td><%= cage.created_by %></td>
    <td><%= cage.modified_on %></td>
    <td><%= cage.bodified_by %></td>
    <td><%= link_to 'Show', cage %></td>
    <td><%= link_to 'Edit', edit_cage_path(cage) %></td>
    <td><%= link_to 'Destroy', cage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cage', new_cage_path %>

app/views/cages/new.html.erb
<h1>New cage</h1>

<%= render 'form' %>

<%= link_to 'Back', cages_path %>

app/views/cages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @cage.label %>
</p>

<p>
  <b>Protocol:</b>
  <%= @cage.protocol_id %>
</p>

<p>
  <b>Mouse rack:</b>
  <%= @cage.mouse_rack_id %>
</p>

<p>
  <b>Row:</b>
  <%= @cage.row %>
</p>

<p>
  <b>Column:</b>
  <%= @cage.column %>
</p>

<p>
  <b>User:</b>
  <%= @cage.user_id %>
</p>

<p>
  <b>Created at:</b>
  <%= @cage.created_at %>
</p>

<p>
  <b>Created by:</b>
  <%= @cage.created_by %>
</p>

<p>
  <b>Modified on:</b>
  <%= @cage.modified_on %>
</p>

<p>
  <b>Bodified by:</b>
  <%= @cage.bodified_by %>
</p>


<%= link_to 'Edit', edit_cage_path(@cage) %> |
<%= link_to 'Back', cages_path %>