config/routes.rb
MousehouseRails::Application.routes.draw do
  resources :buildings

  resources :rooms

  resources :litters

  resources :breeding_pairs

  resources :mice

  resources :cages

  resources :mouse_racks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show
  
  namespace :api do
    namespace :v1  do
      match 'sign_in' => 'tokens#create', :via => :post
      match 'sign_out' => 'tokens#destroy', :via => :post
      #resources :tokens, :only => [:create, :destroy]
      resources :cages
      resources :mouse_racks
    end
  end
  
  
end

app/models/building.rb
class Building
  include Mongoid::Document
  field :institution_id, :type => Integer
  field :label, :type => String
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.json
  def new
    @building = Building.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    @building = Building.find(params[:id])
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :institution_id %><br />
    <%= f.number_field :institution_id %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <tr>
    <th>Institution</th>
    <th>Label</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buildings.each do |building| %>
  <tr>
    <td><%= building.institution_id %></td>
    <td><%= building.label %></td>
    <td><%= link_to 'Show', building %></td>
    <td><%= link_to 'Edit', edit_building_path(building) %></td>
    <td><%= link_to 'Destroy', building, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Institution:</b>
  <%= @building.institution_id %>
</p>

<p>
  <b>Label:</b>
  <%= @building.label %>
</p>


<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>